envs:
  port: 8083
  debug:
    query: DEBUG
    param: DEBUG
  database:
    name: movies-db
    username: dev
    password: dev123
    url: r2dbc:pool:postgres://localhost:5432/${envs.database.name}

server:
  port: ${envs.port}

spring:
  r2dbc:
    url: ${envs.database.url}
    username: ${envs.database.username}
    password: ${envs.database.password}

#  flyway:
#    url: jdbc:postgresql://localhost:5432/fin_api_test_db
#    locations: classpath:db/migration
#    user: ${spring.r2dbc.username}
#    password: ${spring.r2dbc.password}

springdoc:
  swagger-ui:
    path: /v3/swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    io.r2dbc.postgresql.QUERY: ${envs.debug.query}
    io.r2dbc.postgresql.PARAM: ${envs.debug.param}

settings:
  batchSize: 1000